### ISSUE TITLE
`result.it` is wrong if specifying max iterations

### ISSUE THREAD

**Issue by MiniGod** [solzimer/skmeans#11]
I assume `result.it` should be `<= maxIterations`, but is rather a big number (close to `MAX`).

```
const skmeans = require("skmeans")
const data = [1,12,13,4,25,21,22,3,14,5,11,2,23,24,15];

const result = skmeans(data,3,null,10);
console.log(result.it) // 9991
```

I see that `it` is calculated using `MAX - it`, where `MAX = 10000`, and `it` was counted backwards from 10 in this case. Should rather use `maxit` if it is set.

https://github.com/solzimer/skmeans/blob/6c8ffeba3b7b1e220cd34b810f324d71ebd918c5/main.js#L175

**Comment by solzimer** [comment]
Hi @MiniGod ,

You are right. It has been fixed in version [0.11.3](https://www.npmjs.com/package/skmeans)

Thanks for your feedback
