### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by azerella** [solzimer/skmeans#13]
I'm not sure if this has come up in the past but I've submitted some TypeScript definitions for the community at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43059 if that's cool?

**Comment by solzimer** [comment]
Hi @adamzerella,

Thanks for this contribution, it's a nice work!

**Comment by azerella** [comment]
I'll close this issue, just letting you know the types have been published :)

https://www.npmjs.com/package/@types/skmeans
