### ISSUE TITLE
Publish dist/skmeans.js as main

### ISSUE THREAD

**Issue by DenisCarriere** [solzimer/skmeans#3]
I'm trying to import your library into a pure ES5 library, however your `main` in `package.json` is pointing to your ES6 `main.js` instead of your `dist/skmeans.js` (which is ES5 built by browserify/babel).

Would it possible to replace your main with your distributed file.

**Comment by DenisCarriere** [comment]
2nd observation, I couldn't get your browserify bundle to work with NodeJS, normally those Browserify bundles work for both Browser & NodeJS.

Might be something to consider looking into.

```
$ node
> require('./skmeans')
ReferenceError: window is not defined
    at Object.__dirname.1../main.js (/Users/mac/Github/turf/packages/turf-clusters-kmeans/skmeans2.js:21:6)
    at s (/Users/mac/Github/turf/packages/turf-clusters-kmeans/skmeans2.js:8:44)
    at e (/Users/mac/Github/turf/packages/turf-clusters-kmeans/skmeans2.js:13:3)
    at Object.<anonymous> (/Users/mac/Github/turf/packages/turf-clusters-kmeans/skmeans2.js:15:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

**Comment by solzimer** [comment]
Hi @DenisCarriere,

Normally I only use grunt/browserify to export the module to browser only (as a 'window' global variable), because I assume that node users will only use the "require(<module>)". But I will take a look into the issue, providing a more standarized module, with window and require modes for ES5

**Comment by DenisCarriere** [comment]
Thanks for looking into this.

Seems like you are using an outdated browserify library or some configurations are hardcoded for only browser.

I've been able to use this Browserify bundle and it works with Node, so it's not Browserify the issue.

https://wzrd.in/standalone/skmeans@latest

Also ES5 is not only for Browser support, NodeJS 4 doesn't support all the newest fancy gadgets that ES6 has to offer.

**Comment by solzimer** [comment]
Hi @DenisCarriere, I've updated the module to include both, an only browser module, and a ES5 version for Node.

Now, package.json points to the ES5 distribution, so it will work on older node versions, allowing you also to correctly browserify your project.

Current version is [0.9.7](https://github.com/solzimer/skmeans/releases/tag/0.9.7), also published in [npm](https://www.npmjs.com/package/skmeans)

**Comment by DenisCarriere** [comment]
👍 Perfect! Thanks @solzimer 

**FYI:** I've locked the version to `0.9.7`, but if you ever release a major release or a critical patch, just send a PR to [TurfJS](https://github.com/Turfjs/turf/) or `@` me.
