### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fraguada** [solzimer/skmeans#4]
There doesn't seem to be any license attributed to this repo. Please clarify the licensing of this library. BTW, thank you @solzimer for this super simple implementation!

**Comment by solzimer** [comment]
Hi @fraguada,

Thanks for your comments to the library. As you can see in the package.json file, the library is MIT licensed, so you can do whatever you want. You are totally free to use it, extend it, fork it without any permission, either commercially and non commercially.
