### ISSUE TITLE
How to tell which centroid is most common/

### ISSUE THREAD

**Issue by brandonros** [solzimer/skmeans#5]
This might be a stupid question.

I was reading https://adamspannbauer.github.io/2018/03/02/app-icon-dominant-colors/ and stumbled across this library.

The code on that blog article that I'm questioning is:

```
    #cluster and assign labels to the pixels 
    clt = KMeans(n_clusters = k)
    labels = clt.fit_predict(image)

    #count labels to find most popular
    label_counts = Counter(labels)

    #subset out most popular centroid
    dominant_color = clt.cluster_centers_[label_counts.most_common(1)[0][0]]

```

Is it possible to see which centroid cluster is the most common, or is that not really part of the `k-means` method?

**Comment by solzimer** [comment]
Hi @brandonros ,

I don't know if I really understand the question, but I'll try to answer: This algorythm implementation doesn't explicitly give you the most common cluster, but it's easily obtainable, simply counting the elements of each cluster and then getting the one with more items. Suppose, given this result;

```javascript
clusters = {
	it: 2,
	k: 3,
	idxs: [ 2, 2, 0, 2, 1, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0 ],
	centroids: [ 13, 23, 3 ]
}
````
You can do a reduce to count the elements of each cluster:

```javascript
count = clusters.idxs.reduce((map,idx)=>{
    map[a.centroids[idx]] = map[a.centroids[idx]] || 0;
    map[a.centroids[idx]]++;
    return map;
},{});
```

So, **count** will be;

```javascript
{3: 6, 13: 4, 23: 5}
```
Finally, you can sort the keys (cluster centroids) by its length:

```javascript
res = Object.keys(count).sort((a,b)=>count[b] - count[a])
```
Will give yoy the array of centroids sorted by its size:
```javascript
["3", "23", "13"]
```
