### ISSUE TITLE
FR: custom distance function

### ISSUE THREAD

**Issue by salamanders** [solzimer/skmeans#7]
Sometimes two data points should never be put in the same cluster, I'd like to assign them a high distance value in those cases, which I believe would require a custom function.  Ideally something where you could return 1.0 for "big distance" and then call the super method for the real distance in the rest of the cases.

**Comment by solzimer** [comment]
Hi, @salamanders ,

Although k-means works tipically with euclidean distance (or manhattan distance in some cases), I agree with you that there might be some cases where a custom distance function is needed.

Checkout version 0.10.0 where I have introduced this functionality:

`var res = skmeans(data,3,null,null,(x1,x2)=>mycustomfn(x1,x2))`

Thanks for your feedback!
