### ISSUE TITLE
Undefined centroid

### ISSUE THREAD

**Issue by DSergiu** [solzimer/skmeans#8]
When using custom distance function, the passed centroid to the function is undefined. The index for getting the centroid should be **j** instead of **k**. 

https://github.com/solzimer/skmeans/blob/563f3eb442b930dbb8b3f50118b579f12eda95d7/main.js#L58

**Comment by solzimer** [comment]
Hi @DSergiu ,

Sorry for the delay. You are completely right. It has been fixed in version 0.10.2

Thanks for the feedback
