### ISSUE TITLE
skmeans object doesnt have predict method.

### ISSUE THREAD

**Issue by MallyaAni** [solzimer/skmeans#9]
@solzimer I was quite surprised that there was no predict method for the skmeans object. The clustering does a good job but if i want to assign new test examples to a cluster we would need a predict method.

**Comment by solzimer** [comment]
Hi, @MallyaAni,

I've added a new "test" method to the results object, so you can test new points agains the cluster:

```javascript
let data = [1,2,3,4,5,6,7,8,9,10];
let res = skmeans(data,3,null,10);
res.test(6);
```

Current version is [0.11.0](https://www.npmjs.com/package/skmeans/v/0.11.0)

Thanks for the feedback!

**Comment by MallyaAni** [comment]
@solzimer Thanks! this helps a lot. I verified it, it's accurate :)
